# Generated by Django 6.0.2 on 2026-02-06 06:08

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100, verbose_name='Prénom')),
                ('lastname', models.CharField(max_length=100, verbose_name='Nom de famille')),
                ('title', models.CharField(max_length=100, verbose_name='Titre')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Biographie')),
                ('birth_date', models.DateField(verbose_name='Date de naissance')),
                ('image', models.ImageField(blank=True, null=True, upload_to='artists/', verbose_name="Image de l'artiste")),
            ],
            options={
                'verbose_name': 'Artiste',
                'verbose_name_plural': 'Artistes',
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legend', models.CharField(max_length=100, verbose_name='Légende')),
                ('title', models.CharField(max_length=100, verbose_name='Titre')),
                ('paragraph_1', models.TextField(blank=True, null=True, verbose_name='Paragraphe 1')),
                ('paragraph_2', models.TextField(blank=True, null=True, verbose_name='Paragraphe 2')),
                ('paragraph_3', models.TextField(blank=True, null=True, verbose_name='Paragraphe 3')),
                ('quote', models.TextField(blank=True, null=True, verbose_name='Citation')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name="Image d'illustration")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
            ],
            options={
                'verbose_name': 'Article de blog',
                'verbose_name_plural': 'Articles de blog',
            },
        ),
        migrations.CreateModel(
            name='Exposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titre')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(verbose_name='Date de fin')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='exhibitions/', verbose_name="Image d'illustration")),
            ],
            options={
                'verbose_name': 'Exposition',
                'verbose_name_plural': 'Expositions',
            },
        ),
        migrations.CreateModel(
            name='Tableau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='paintings/', verbose_name='Image du tableau')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Prix')),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('sold', 'Vendu'), ('reserved', 'Réservé')], default='available', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
            ],
            options={
                'verbose_name': 'Tableau',
                'verbose_name_plural': 'Tableaux',
            },
        ),
    ]
