# Generated by Django 6.0.2 on 2026-02-06 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarrierePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('title', models.CharField(max_length=100, verbose_name='Titre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='carriere/', verbose_name="Image d'illustration")),
            ],
            options={
                'verbose_name': 'Point de ma carrière',
                'verbose_name_plural': 'Points de ma carrière',
            },
        ),
        migrations.AlterModelOptions(
            name='artist',
            options={'verbose_name': "L'Artiste", 'verbose_name_plural': "L'Artiste"},
        ),
    ]
