# Generated by Django 6.0.2 on 2026-02-06 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_carrierepoint_alter_artist_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='OriginalCreation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titre')),
                ('image', models.ImageField(blank=True, null=True, upload_to='original_creations/', verbose_name="Image de l'œuvre")),
            ],
            options={
                'verbose_name': 'Œuvre originale',
                'verbose_name_plural': 'Œuvres originales',
            },
        ),
    ]
