# Generated by Django 6.0.2 on 2026-02-06 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_originalcreation'),
    ]

    operations = [
        migrations.AddField(
            model_name='originalcreation',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
