# Generated by Django 6.0.2 on 2026-02-07 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_originalcreation_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='bio',
        ),
        migrations.AddField(
            model_name='artist',
            name='paragraphe',
            field=models.TextField(blank=True, null=True, verbose_name='Biographie paragraphe 1'),
        ),
        migrations.AddField(
            model_name='artist',
            name='paragraphe_2',
            field=models.TextField(blank=True, null=True, verbose_name='Biographie paragraphe 2'),
        ),
        migrations.AddField(
            model_name='artist',
            name='paragraphe_3',
            field=models.TextField(blank=True, null=True, verbose_name='Biographie paragraphe 3'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Titre Biographie'),
        ),
    ]
